version: '3.9'

services:
  app:
    image: example-rest-on-go
    container_name: example-rest-on-go
    build: ./
    env_file:
      - .env
    ports:
      -8000:8000
    depends_on:
      - db

    db:
      restart: always
      image: postgres:latest
      volumes:
        - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
      ports:
        - 5432:5432